# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpRunbatch < Formula
  desc ""
  homepage "https://github.com/bitcomplete/gcp-runbatch"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/gcp-runbatch/releases/download/v0.1.0/gcp-runbatch_0.1.0_Darwin_arm64.tar.gz"
      sha256 "35ea2732f0f080aa18ac2737613062412aa008fae05e032fffc3d43d553a7afa"

      def install
        bin.install "gcp-runbatch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/gcp-runbatch/releases/download/v0.1.0/gcp-runbatch_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a6d333fe9b6fc183250ec37fb207cb39bdf848d41bb044e588a63bbce8bad7c6"

      def install
        bin.install "gcp-runbatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/gcp-runbatch/releases/download/v0.1.0/gcp-runbatch_0.1.0_Linux_x86_64.tar.gz"
      sha256 "de0dec23f3e0e3d54a8062588d4c83054921ea3de753f81b1ed6e3b715660256"

      def install
        bin.install "gcp-runbatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/gcp-runbatch/releases/download/v0.1.0/gcp-runbatch_0.1.0_Linux_arm64.tar.gz"
      sha256 "e44ba58e0d65c412f1e1d1dd407a2f33ccde2dca15180d918f73d71966404ffe"

      def install
        bin.install "gcp-runbatch"
      end
    end
  end

  test do
    system "#{bin}/gcp-runbatch --version"
  end
end
