# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plz < Formula
  desc "plz CLI"
  homepage "https://plz.review"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.3.4/plz_0.3.4_Darwin_arm64.tar.gz"
      sha256 "b6703505b7f73524dd72b4f438eed225cec342903d52a87252377419e34afb52"

      def install
        bin.install "plz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.3.4/plz_0.3.4_Darwin_x86_64.tar.gz"
      sha256 "4e829f4e27e7a2245e8537b6bd26c933518f89e04861c6d4e2fc4a5f8aaef5af"

      def install
        bin.install "plz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.3.4/plz_0.3.4_Linux_x86_64.tar.gz"
      sha256 "34ff1b1a3cd2c3274694275fcc260d667a6d3af01981b3e0f20ea670e10336ff"

      def install
        bin.install "plz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.3.4/plz_0.3.4_Linux_arm64.tar.gz"
      sha256 "d34b9fa11bf0cfa805ffe15a9e6d693c9820e87c08640c1e04c6b64930fbce7e"

      def install
        bin.install "plz"
      end
    end
  end

  test do
    system "#{bin}/plz --version"
  end
end
