# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plz < Formula
  desc "plz CLI"
  homepage "https://plz.review"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.2.1/plz_0.2.1_Darwin_arm64.tar.gz"
      sha256 "f40fd521f26d91a7c8fdb6860c73b63ad1a52504bf476a973a2c066218a2169e"

      def install
        bin.install "plz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.2.1/plz_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "6268b6bdeb72edb895605a9d72e3e0ec7ad059acf217944441e0866b3520c657"

      def install
        bin.install "plz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.2.1/plz_0.2.1_Linux_x86_64.tar.gz"
      sha256 "b10b1d85162a8f1f5eb7f00c9ca04fd00fa2879687784b924def72ac8c4dc51a"

      def install
        bin.install "plz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/plz-cli/releases/download/v0.2.1/plz_0.2.1_Linux_arm64.tar.gz"
      sha256 "543aa34f3353e5cf9fc14cbad174f022831b290f425caa1281c821436f6434dc"

      def install
        bin.install "plz"
      end
    end
  end

  test do
    system "#{bin}/plz --version"
  end
end
