# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kploy < Formula
  desc "CLI for managing Kploy environments"
  homepage "https://github.com/bitcomplete/kploy-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/kploy-cli/releases/download/v0.1.0/kploy_0.1.0_darwin_amd64.tar.gz"
      sha256 "c9e26449175490a4f852f305163c82cac6cca8c7a90e39808a1f7872e89a2684"

      define_method(:install) do
        bin.install "kploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/kploy-cli/releases/download/v0.1.0/kploy_0.1.0_darwin_arm64.tar.gz"
      sha256 "4bb115c3f290414cc8603e93c485233de5b4460c18e652df5f3a19aa12c76d8f"

      define_method(:install) do
        bin.install "kploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/kploy-cli/releases/download/v0.1.0/kploy_0.1.0_linux_amd64.tar.gz"
      sha256 "7245fc6bff6f8cf6056e795adec7a096e80f830a65029abf0602ae965d727e8f"
      define_method(:install) do
        bin.install "kploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/kploy-cli/releases/download/v0.1.0/kploy_0.1.0_linux_arm64.tar.gz"
      sha256 "68d8f77d921e4feee5c8cc092f2db348d17f204d047f6aa387a9eda3e7c7a100"
      define_method(:install) do
        bin.install "kploy"
      end
    end
  end

  test do
    assert_match "kploy", shell_output("#{bin}/kploy --help")
  end
end
