# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kploy < Formula
  desc "CLI for managing Kploy environments"
  homepage "https://github.com/bitcomplete/kploy"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/homebrew-tap/releases/download/v0.2.0/kploy_0.2.0_darwin_amd64.tar.gz"
      sha256 "9be7d661521f2dd3e51635548b85e17b6027d967000b7242b9b58afda53b2508"

      define_method(:install) do
        bin.install "kploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/homebrew-tap/releases/download/v0.2.0/kploy_0.2.0_darwin_arm64.tar.gz"
      sha256 "6e190601ebacd6cf76a850250e4dd4f12b323580e87fd41b96c01f4eb570651e"

      define_method(:install) do
        bin.install "kploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/homebrew-tap/releases/download/v0.2.0/kploy_0.2.0_linux_amd64.tar.gz"
      sha256 "627b15d7b63b59b0bc8e54fc547f68f6c5fea19e027992a154236e88ad3715e2"
      define_method(:install) do
        bin.install "kploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/homebrew-tap/releases/download/v0.2.0/kploy_0.2.0_linux_arm64.tar.gz"
      sha256 "c6090af4789595c08052f2584d39b7c02b35bd77554f93149b0edd99571af4cf"
      define_method(:install) do
        bin.install "kploy"
      end
    end
  end

  test do
    assert_match "kploy", shell_output("#{bin}/kploy --help")
  end
end
