# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pin < Formula
  desc "Command-line client for pin (HTML sharing service)"
  homepage "https://github.com/bitcomplete/pin-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.4.0/pin_0.4.0_darwin_amd64.tar.gz"
      sha256 "df6916e08402b12ecfe0da7402567cff52ac0ffb9a54f691af879c34e73b7fad"

      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.4.0/pin_0.4.0_darwin_arm64.tar.gz"
      sha256 "6a2f7779abeeceec5f35aea302e7ce0110aad2d62fed48b8b57e002982d1086c"

      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.4.0/pin_0.4.0_linux_amd64.tar.gz"
      sha256 "51d4e6071e235f640360ab500e8216a4ffac314100827e1fd397b7883e1fc9b5"
      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.4.0/pin_0.4.0_linux_arm64.tar.gz"
      sha256 "5e23ffc1ded06854dd223b669379459f80b3bcfbbb4896163689b93bb61a6a11"
      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  test do
    assert_match "pin", shell_output("#{bin}/pin --help")
  end
end
