# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pin < Formula
  desc "Command-line client for pin (HTML sharing service)"
  homepage "https://github.com/bitcomplete/pin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.1.0/pin_0.1.0_darwin_amd64.tar.gz"
      sha256 "dd64d8673579684a7381dfbe13c4088bc519f8f75de3bd31fb60005f4da3ca98"

      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.1.0/pin_0.1.0_darwin_arm64.tar.gz"
      sha256 "fc6a6a022807b1ceb1a7d7c1b5c3de3b914524c9f3dfd928f4b1fb4876b1a8c3"

      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.1.0/pin_0.1.0_linux_amd64.tar.gz"
      sha256 "d82c4f659c5dad83735c80736cbdbebc7799e4d6b7190e95e2f3686f97803380"
      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.1.0/pin_0.1.0_linux_arm64.tar.gz"
      sha256 "07c665d61546b97d422e81a210d283e7c5f880bf471d2132f905138734fa1c1c"
      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  test do
    assert_match "pin", shell_output("#{bin}/pin --help")
  end
end
