# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pin < Formula
  desc "Command-line client for pin (HTML sharing service)"
  homepage "https://github.com/bitcomplete/pin-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.3.0/pin_0.3.0_darwin_amd64.tar.gz"
      sha256 "3f3a15aff0628a0a24de41229ad7eed20f4c60067b78a2046098fb4d80383fec"

      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.3.0/pin_0.3.0_darwin_arm64.tar.gz"
      sha256 "54c01cc0be75eb2b6e57a53e2b39d9f18ed6fa3c2faf6678aef6bc4a68e8a528"

      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.3.0/pin_0.3.0_linux_amd64.tar.gz"
      sha256 "4d21a08d47a23a008ba78a8012b04bf90243c13e95ba2044fe5e39e459c8aa4a"
      define_method(:install) do
        bin.install "pin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcomplete/pin-cli/releases/download/v0.3.0/pin_0.3.0_linux_arm64.tar.gz"
      sha256 "ada9c1e92268216f842333d22491fdd8ad55492145a77bebaaffe8c3aed82471"
      define_method(:install) do
        bin.install "pin"
      end
    end
  end

  test do
    assert_match "pin", shell_output("#{bin}/pin --help")
  end
end
